name: Docker Compose Up and Logs

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d
      working-directory: .

    - name: Sleep for a while to wait for containers to start
      run: sleep 10s

    - name: Get Container Name
      id: container_name
      run: echo "::set-output name=name::$(docker-compose ps -q hackaton)"

    - name: Get Docker Logs
      run: |
        docker logs ${{ steps.container_name.outputs.name }} > logs.txt
      working-directory: .

    - name: Display Logs
      run: cat logs.txt