spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    # use this line to te on your localhost
    # url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
